### ISSUE TITLE
彻底删库跑路Liteyuki4.0项目

### ISSUE THREAD

**Issue by Hymomo** [snowykami/LiteyukiBot#26]
众所周知，Liteyuki4.0项目是基于NoneBot的第二代机器人，拥有很宽泛的兼容性，有着仅次于云崽和喵端的使用量，并且此项目还是开源的，意味着任何人都有权利可以发表自己的意见或提交申请，但是，今天，Liteyuki4.0项目就要解散了!

**_因为Liteyuki5.0就要来啦Doge_**

**Comment by snowykami** [comment]
会说话就多说点

**Comment by tamakyi** [comment]
靠北 我说突然怎么pull报错

**Comment by Hymomo** [comment]
> 靠北 我说突然怎么拉报错

笑死了
