### ISSUE TITLE
依赖安装报错

### ISSUE THREAD

**Issue by QSlotus** [snowykami/LiteyukiBot#27]
如题
报错如下
```
ERROR: Could not find a version that satisfies the requirement yaml==0.2.5 (from versions: none)
ERROR: No matching distribution found for yaml==0.2.5
```

**Comment by snowykami** [comment]
这个项目已经暂时跑路了[pr-25](https://github.com/snowykami/LiteyukiBot/pull/25)，目前这个版本的LiteyukiBot还不能用，我自己都没测试过，等后续我的MCBot完成后我会来重构这个项目的

**Comment by snowykami** [comment]
现在最新版本的应该不会了，之前是由于我把`PyYaml`错误写为了`yaml`所致
