### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Starrain08** [snowykami/LiteyukiBot#36]
由于LLonebot不支持发送markdown消息，导致所有点击操作无法使用，能否出一个兼容，可以在markdown消息和图片消息之间转换
![image](https://github.com/snowykami/LiteyukiBot/assets/119772101/b6511b1d-5713-47ca-9c58-703e057573e2)
![image](https://github.com/snowykami/LiteyukiBot/assets/119772101/107f196d-ea78-4563-a83e-bb56c759f570)
QQ也目前在修复，个人无法发送markdown消息

**Comment by snowykami** [comment]
因为QQ那边把野生bot的markdown权限彻底杀死了，llonebot本身不支持发送md，其他实现端因为tx的围追堵截现在也无法发送md了，目前只能以图片的形式渲染菜单，因此无法进行点击操作，不过所有的点击操作都是整合命令实现的，你仍然可以使用命令进行操作。

目前也没想到更好的方案了，或许未来可以把提示命令也写在图片菜单里面

**Comment by 2055135** [comment]
> 因为QQ那边把野生bot的markdown权限彻底杀死了，llonebot本身不支持发送md，其他实现端因为tx的围追堵截现在也无法发送md了，目前只能以图片的形式渲染菜单，因此无法进行点击操作，不过所有的点击操作都是整合命令实现的，你仍然可以使用命令进行操作。
> 
> 目前也没想到更好的方案了，或许未来可以把提示命令也写在图片菜单里面

可以试试呢，真寻bot都是把命令这些直接写进图片里的
