### ISSUE TITLE
📝 Docs: 是否有计划撰写多语言版本Liteyuki Docs?

### ISSUE THREAD

**Issue by Nanaloveyuki** [snowykami/LiteyukiBot#43]
翻阅pr记录~~闲~~时看到几个对md多语言化的pr被合并了, 按照[官网](https://bot.liteyuki.icu)的罗列特点来看, 既然是多平台支持, 且要国际化, 那么文档多语言应该是必不可少的. 

如果要撰写多语言版本, 有以下几个问题:
1. 多语言文档的存放位置: `/Docs/? `
2. 多语言文档的支持语种?
3. 多语言文档的翻译方式?

如果无需撰写多语言版本, 则关闭本Issues即可.

**Comment by snowykami** [comment]
可以有，/zh/ /en/这种

**Comment by snowykami** [comment]
具体可以看下vuepress相关文档
